[lint]
select = ["E4", "E7", "E9", "F", "D"]
ignore = ["D100", "D102", "D103", "D104"]

[lint.pydocstyle]
convention = "numpy"

[format]
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true

[tool.isort]
profile = "black"
force_sort_within_sections = true  # Don't group `from` imports separately
order_by_type = true  # Order by CONSTANT, CamelCase, snake_case
